<?php

/**
 * @file
 * Contains utprof content type .module file.
 */

use Drupal\Core\File\FileSystemInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Language\Language;
use Drupal\Core\Link;
use Drupal\Core\Url;
use Drupal\file\Entity\File;
use Drupal\media\Entity\Media;
use Drupal\node\Entity\Node;
use Drupal\utprof_content_type_profile\Form\FormAlter;

/**
 * Implements hook_theme().
 */
function utprof_content_type_profile_theme() {
  return [
    'node__utprof_profile' => [
      'template' => 'node--utprof-profile',
      'base hook' => 'node',
    ],
    'node__utprof_profile__utexas_basic' => [
      'template' => 'node--utprof-profile--utexas-basic',
      'base hook' => 'node',
    ],
    'node__utprof_profile__utexas_prominent' => [
      'template' => 'node--utprof-profile--utexas-prominent',
      'base hook' => 'node',
    ],
    'node__utprof_profile__utexas_name_only' => [
      'template' => 'node--utprof-profile--utexas-name-only',
      'base hook' => 'node',
    ],
    'field__node__utprof_profile' => [
      'template' => 'field--node--utprof-profile',
      'base hook' => 'field',
    ],
  ];
}

/**
 * Implements hook_preprocess_node().
 */
function utprof_content_type_profile_preprocess_node(&$variables) {
  $node = $variables['elements']['#node'];
  $type = $node->getType();
  if ($type === 'utprof_profile' && $variables['view_mode'] == 'full') {
    $variables['#attached']['library'][] = 'utprof_content_type_profile/node-display';

    // Build EID link.
    if ($node->hasField('field_utprof_eid') && !$node->get('field_utprof_eid')->isEmpty()) {
      $eid = $node->get('field_utprof_eid');
      $url = Url::fromUri('https://directory.utexas.edu/index.php?q=' . $eid->getString());
      $link_options = [
        'attributes' => [
          'class' => [
            'ut-btn',
          ],
        ],
      ];
      $url->setOptions($link_options);
      $variables['directory_link'] = Link::fromTextAndUrl(t('View in Directory'), $url);
    }

    // Build contact form link.
    if ($node->hasField('field_utprof_contact_form_link') && !$node->get('field_utprof_contact_form_link')->isEmpty()) {
      $contact_link = $node->get('field_utprof_contact_form_link');
      $contact_values = $contact_link->getValue();
      $url = Url::fromUri($contact_values[0]['uri']);
      $link_options = [
        'attributes' => [
          'class' => [
            'ut-btn',
          ],
        ],
      ];
      $url->setOptions($link_options);
      $variables['contact_form_link'] = Link::fromTextAndUrl(t($contact_values[0]['title']), $url);
    }

    // Build basic media (headshot).
    if ($node->hasField('field_utprof_basic_media') && !$node->get('field_utprof_basic_media')->isEmpty()) {
      $headshot = $node->get('field_utprof_basic_media');

      if ($node->hasField('field_utprof_image_ratio_opt') && !$node->get('field_utprof_image_ratio_opt')->isEmpty()) {
        $use_primary_image_style = $node->get('field_utprof_image_ratio_opt');
      }

      $user_defined_image_style = $use_primary_image_style ? 'utexas_image_style_500w_500h' : 'utexas_image_style_500w';
      if ($media = \Drupal::entityTypeManager()->getStorage('media')->load($headshot->getString())) {
        $image_render_array = $media->field_utexas_media_image->view([
          'type' => 'image',
          'label' => 'hidden',
          'settings' => [
            'image_style' => $user_defined_image_style,
            'image_link' => '',
          ],
        ]);
        $variables['basic_media'] = $image_render_array;
      }
    }

    // Build Building Information link.
    $building_code_value = NULL;
    $building_code_link = NULL;
    if ($node->hasField('field_utprof_building_code') && !$node->get('field_utprof_building_code')->isEmpty()) {
      $building_code = $node->get('field_utprof_building_code');
      $url = Url::fromUri('https://utdirect.utexas.edu/apps/campus/buildings/nlogon/maps/UTM/' . $building_code->getString());
      $building_code = Link::fromTextAndUrl($building_code, $url);
      $building_code_value = $building_code->getText()->getValue()[0]['value'];
      $building_code_link = $building_code->getUrl()->getUri();
    }

    $building_room_value = NULL;
    if ($node->hasField('field_utprof_building_room_numb') && !$node->get('field_utprof_building_room_numb')->isEmpty()) {
      $building_room_value = $node->get('field_utprof_building_room_numb')->getString();
    }
    $variables['building_information']['code_value'] = $building_code_value ?? NULL;
    $variables['building_information']['code_link'] = $building_code_link ?? NULL;
    $variables['building_information']['room_number'] = $building_room_value ?? NULL;

    // Build phone number link.
    if ($node->hasField('field_utprof_phone_number') && !$node->get('field_utprof_phone_number')->isEmpty()) {
      $phone_number = $node->get('field_utprof_phone_number');
      $phone_number_text = $phone_number->getString();
      $phone_link = Url::fromUri('tel:' . rawurlencode($phone_number_text));
      $variables['phone_link'] = Link::fromTextAndUrl($phone_number_text, $phone_link);
    }

    $has_contact_info = FALSE;
    foreach (FormAlter::UTPROF_CONTENT_TYPE_PROFILE_CONTACT_INFO_FIELDS as $contact_info_field) {
      if ($node->hasField($contact_info_field) && !$node->$contact_info_field->isEmpty()) {
        $has_contact_info = TRUE;
        break;
      }
    }
    $variables['has_contact_info'] = $has_contact_info;
  }
}

/**
 * Implements hook_form_alter().
 */
function utprof_content_type_profile_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (in_array($form_id, ['node_utprof_profile_edit_form', 'node_utprof_profile_form'])) {
    $alter = \Drupal::classResolver(FormAlter::class);
    $alter->alterProfileNodeForm($form, $form_state, $form_id);
  }
}

/**
 * Helper function to create a media item.
 *
 * @param array $image_metadata
 *   Key-value pair for a media item.
 *
 * @return int
 *   The media MID.
 */
function _utprof_content_type_profile_create_media(array $image_metadata) {
  $file_system = \Drupal::service('file_system');
  $filedir = 'public://utexas_devel/';
  $file_system->prepareDirectory($filedir, FileSystemInterface::CREATE_DIRECTORY);
  $image = File::create();
  $image->setFileUri($image_metadata['filepath']);
  $image->setOwnerId(\Drupal::currentUser()->id());
  $image->setMimeType(\Drupal::service('file.mime_type.guesser')->guess($image_metadata['filepath']));
  $image->setFileName($file_system->basename($image_metadata['filepath']));
  $destination_dir = 'public://generated_sample';
  $file_system->prepareDirectory($destination_dir, FileSystemInterface::CREATE_DIRECTORY);
  $destination = $destination_dir . '/' . basename($image_metadata['filepath']);
  $file = file_copy($image, $destination);
  $image_media = Media::create([
    'name' => $image_metadata['filename'],
    'bundle' => 'utexas_image',
    'uid' => '1',
    'langcode' => Language::LANGCODE_NOT_SPECIFIED,
    'status' => '1',
    'field_utexas_media_image' => [
      'target_id' => $file->id(),
      'alt' => $image_metadata['alt_text'],
      'title' => $image_metadata['title_text'],
    ],
  ]);
  $image_media->save();
  return $image_media->id();
}

/**
 * Helper function to create a Profile node.
 *
 * @param array $data
 *   Key-value array of field data.
 */
function _utprof_content_type_profile_create_node(array $data) {
  $node = Node::create(['type' => 'utprof_profile']);
  $node->set('title', $data['title']);
  $node->set('uid', '1');
  foreach ($data['fields'] as $machine_name => $field_data) {
    $node->set($machine_name, $field_data);
  }
  foreach ($data['profile_groups'] as $group_name) {
    $term = \Drupal::entityTypeManager()->getStorage('taxonomy_term')
      ->loadByProperties(['name' => $group_name, 'vid' => 'utprof_groups']);
    $group = reset($term);
    $group_tids[] = $group->id();
  }
  $node->set('field_utprof_profile_groups', $group_tids);
  if (isset($data['basic_media'])) {
    $media_mid = _utprof_content_type_profile_create_media($data['basic_media']);
    $node->set('field_utprof_basic_media', $media_mid);
  }
  $node->status = 1;
  $node->enforceIsNew();
  $node->save();
}
