<?php

/**
 * @file
 * Contains utprof content type .module file.
 */

use Drupal\Core\Link;
use Drupal\Core\File\FileSystemInterface;
use Drupal\Core\Language\Language;
use Drupal\Core\Url;
use Drupal\file\Entity\File;
use Drupal\media\Entity\Media;
use Drupal\node\Entity\Node;

/**
 * Implements hook_theme().
 */
function utprof_content_type_profile_theme() {
  return [
    'node__utprof_profile' => [
      'template' => 'node--utprof-profile',
      'base hook' => 'node',
    ],
  ];
}

/**
 * Implements hook_preprocess_node().
 */
function utprof_content_type_profile_preprocess_node(&$variables) {
  $variables['#attached']['library'][] =  'utprof_content_type_profile/utprof';
  $node = $variables['elements']['#node'];
  $type = $node->getType();
  if ($type === 'utprof_profile') {

    $eid = $node->get('field_utprof_eid');
    if (!$eid->isEmpty()) {
      $url = Url::fromUri('https://directory.utexas.edu/index.php?q=' . $eid->getString());
      $link_options = [
        'attributes' => [
          'class' => [
            'ut-btn',
          ],
        ],
      ];
      $url->setOptions($link_options);
      $variables['directory_link'] = Link::fromTextAndUrl(t('View in Directory'), $url);
    }

    $contact_link = $node->get('field_utprof_contact_form_link');
    if (!$contact_link->isEmpty()) {
      $contact_values = $contact_link->getValue();
      $url = Url::fromUri($contact_values[0]['uri']);
      $link_options = [
        'attributes' => [
          'class' => [
            'ut-btn',
          ],
        ],
      ];
      $url->setOptions($link_options);
      $variables['contact_form_link'] = Link::fromTextAndUrl(t($contact_values[0]['title']), $url);
    }

    $headshot = $node->get('field_utprof_basic_media');
    if (!$headshot->isEmpty()) {
      $user_defined_image_style = $node->get('field_utprof_image_ratio_opt')->getString() == 1 ? 'utexas_image_style_500w_500h' : 'utexas_image_style_500w';
      if ($media = \Drupal::entityTypeManager()->getStorage('media')->load($headshot->getString())) {
        $image_render_array = $media->field_utexas_media_image->view([
          'type' => 'image',
          'label' => 'hidden',
          'settings' => [
            'image_style' => $user_defined_image_style,
            'image_link' => '',
          ],
        ]);
        $variables['basic_media'] = $image_render_array;
      }
    }

    $building_code = $node->get('field_utprof_building_code');
    if (!$building_code->isEmpty()) {
      $url = Url::fromUri('https://utdirect.utexas.edu/apps/campus/buildings/nlogon/maps/UTM/' . $building_code->getString());
      $variables['building_code'] = Link::fromTextAndUrl($building_code, $url);
    }

    $contact_info_fields = [
      'field_utprof_email_address',
      'field_utprof_website_link',
      'field_utprof_phone_number',
      'field_utprof_fax_number',
      'field_utprof_building_code',
      'field_utprof_building_room_numb',
      'field_utprof_contact_form_link',
      'field_utprof_add_contact_info',
    ];

    $has_contact_info = FALSE;
    foreach ($contact_info_fields as $contact_info_field) {
      if ($node->hasField($contact_info_field) && !$node->$contact_info_field->isEmpty()) {
        $has_contact_info = TRUE;
        break;
      }
    }
    $variables['has_contact_info'] = $has_contact_info;
  }
}

/**
 * Helper function to create a media item.
 *
 * @param array $image_metadata
 *   Key-value pair for a media item.
 *
 * @return int
 *   The media MID.
 */
function _utprof_content_type_profile_create_media(array $image_metadata) {
  $file_system = \Drupal::service('file_system');
  $filedir = 'public://utexas_devel/';
  $file_system->prepareDirectory($filedir, FileSystemInterface::CREATE_DIRECTORY);
  $image = File::create();
  $image->setFileUri($image_metadata['filepath']);
  $image->setOwnerId(\Drupal::currentUser()->id());
  $image->setMimeType(\Drupal::service('file.mime_type.guesser')->guess($image_metadata['filepath']));
  $image->setFileName($file_system->basename($image_metadata['filepath']));
  $destination_dir = 'public://generated_sample';
  $file_system->prepareDirectory($destination_dir, FileSystemInterface::CREATE_DIRECTORY);
  $destination = $destination_dir . '/' . basename($image_metadata['filepath']);
  $file = file_copy($image, $destination);
  $image_media = Media::create([
    'name' => $image_metadata['filename'],
    'bundle' => 'utexas_image',
    'uid' => '1',
    'langcode' => Language::LANGCODE_NOT_SPECIFIED,
    'status' => '1',
    'field_utexas_media_image' => [
      'target_id' => $file->id(),
      'alt' => $image_metadata['alt_text'],
      'title' => $image_metadata['title_text'],
    ],
  ]);
  $image_media->save();
  return $image_media->id();
}

/**
 * Helper function to create a Profile node.
 *
 * @param array $data
 *   Key-value array of field data.
 */
function _utprof_content_type_profile_create_node(array $data) {
  $node = Node::create(['type' => 'utprof_profile']);
  $node->set('title', $data['title']);
  $node->set('uid', '1');
  foreach ($data['fields'] as $machine_name => $field_data) {
    $node->set($machine_name, $field_data);
  }
  foreach ($data['profile_groups'] as $group_name) {
    $term = \Drupal::entityTypeManager()->getStorage('taxonomy_term')
      ->loadByProperties(['name' => $group_name, 'vid' => 'utprof_groups']);
    $group = reset($term);
    $group_tids[] = $group->id();
  }
  $node->set('field_utprof_profile_groups', $group_tids);
  if (isset($data['basic_media'])) {
    $media_mid = _utprof_content_type_profile_create_media($data['basic_media']);
    $node->set('field_utprof_basic_media', $media_mid);
  }
  $node->status = 1;
  $node->enforceIsNew();
  $node->save();
}
