<?php

/**
 * @file
 * Profile Groups vocabulary installation file.
 */

use Drupal\taxonomy\Entity\Term;

/**
 * Implements hook_install().
 */
function utprof_vocabulary_groups_install() {
  $profile_groups = ['Leadership', 'Faculty', 'Staff'];
  $weight = 0;
  foreach ($profile_groups as $term) {
    Term::create([
      'name' => $term,
      'vid' => 'utprof_groups',
      'weight' => $weight,
    ])->save();
    $weight++;
  }
}
