<?php

/**
 * @file
 * Contains utprof profiles view .module file.
 */

/**
 * Implements hook_preprocess_views_view() for the 'utprof_profiles' view.
 */
function utprof_view_profiles_preprocess_views_view__utprof_profiles(array &$variables) {
  if ($variables['view']->current_display == 'block_utprof_profile_listing') {
    $variables['#attached']['library'][] = 'utprof_view_profiles/views-view-list';
  }
}
